In [1]:
import torch

In [25]:
# 创建张量tensor
a = torch.Tensor([[1,2],[3,4],[5,6]])
a_int = a.int()
print(a)
print(a_int)
print(a.size())

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[1, 2],
        [3, 4],
        [5, 6]], dtype=torch.int32)
torch.Size([3, 2])


In [20]:
# 创建全0和全1张量
b = torch.zeros(3,4)
print(b)
c = torch.ones(5,5)
print(c)
# 创建size和a相同的全1张量
d = torch.ones_like(a)
print(d)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [16]:
# tensor和numpy之间的转换
a_numpy = a.numpy()
print(a_numpy)

a_tensor = torch.from_numpy(a_numpy)
print(a_tensor)

[[1. 2.]
 [3. 4.]
 [5. 6.]]
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [22]:
# 将tensor送入gpu送回cpu的方法1
if torch.cuda.is_available():
    a_cuda_1 = a.cuda()
print(a_cuda_1)
a_cpu_1 = a_cuda_1.cpu()
print(a_cpu_1)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], device='cuda:0')
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [23]:
# 将tensor送入gpu送回cpu的方法2
device=torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
a_cuda_2 = a.to(device)
print(a_cuda_2)
a_cpu_2 = a_cuda_2.to(torch.device('cpu'))
print(a_cpu_2)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], device='cuda:0')
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
